spring:
  datasource:
    url: jdbc:h2:file:/home/costea/Work/Arezzosky/TechHerbert2019/Data/cities
    username: test
    password: ""
    driver-class-name: org.h2.Driver

server:
  port: 8080
  tomcat:
    min-spare-threads: 2
    max-threads: 10
    max-connections: 600